# conda env create --file environment.yml
# conda env update --file environment.yml --prune
name: multimedia_systems
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy
    - scipy 
    - matplotlib
    - Pandas
    - python-docx 
    - soundfile
    - sounddevice 
    - Pillow
    - pylibjpeg-libjpeg
    - opencv-contrib-python
    - scikit-learn
    - scikit-image
    - pytest